version: "3.8"

services:
  db:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    restart: always
    environment:
      COCKROACH_DATABASE: sdc
      COCKROACH_USER: sdc
      COCKROACH_PASSWORD: sdc_password
    volumes:
      - ${PWD}/cockroachdb:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8080:8080"

volumes:
  cockroachdb:
